# Generated by Django 5.2.8 on 2025-11-18 04:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeName', models.CharField(max_length=100)),
                ('shoeDescription', models.CharField(max_length=200)),
                ('shoePrice', models.CharField(max_length=100)),
                ('shoeCoverImage', models.ImageField(upload_to='shoesCoverImage/')),
                ('shoeInnerDescription', models.TextField()),
                ('shoeColorName', models.CharField(max_length=200)),
                ('shoeStyleName', models.CharField(max_length=100)),
                ('shoeOriginCountry', models.CharField(max_length=100)),
                ('shoeMainImage', models.ImageField(upload_to='shoesMainImage/')),
                ('shoeMainImage2', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage3', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage4', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage5', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage6', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage7', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage8', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
                ('shoeMainImage9', models.ImageField(blank=True, null=True, upload_to='shoesMainImage/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.EmailField(max_length=100, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
